In [1]:
#Importing libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sklearn as sk
import glob
import seaborn as sns
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import accuracy_score

In [2]:
#Creating the Training dataframe
path = r'/home/harindu/Assignment_II/accel_data_1' 
all_files = glob.glob(path + "/*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=None)
    li.append(df)

activityDF = pd.concat(li, axis=0, ignore_index=True)

In [3]:
#Creating the Testing dataframe
path = r'/home/harindu/Assignment_II/accel_data_test' 
all_files = glob.glob(path + "/*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=None)
    li.append(df)

activityDF_Test = pd.concat(li, axis=0, ignore_index=True)

In [4]:
activityDF_Test.columns = ['index', 'xAccel', 'yAccel', 'zAccel', 'activity']
activityDF_Test = activityDF_Test.drop(['index'], axis=1)

In [5]:
activityDF_Test = activityDF_Test.drop(activityDF_Test[activityDF_Test.activity == 0].index)

In [6]:
activityDF.columns = ['index', 'xAccel', 'yAccel', 'zAccel', 'activity']

In [7]:
activityDF

index  xAccel  yAccel  zAccel  activity
0             0.0    1502    2215    2153         1
1             1.0    1667    2072    2047         1
2             2.0    1611    1957    1906         1
3             3.0    1601    1939    1831         1
4             4.0    1643    1965    1879         1
...           ...     ...     ...     ...       ...
1431437  140900.0    2098    2305    1982         7
1431438  140900.0    2106    2314    1980         7
1431439  140900.0    2112    2319    1973         7
1431440  140900.0    2111    2319    1969         7
1431441  140900.0    2110    2312    1972         0

[1431442 rows x 5 columns]

In [8]:
activityDF = activityDF.drop(['index'], axis=1)

In [9]:
activityDF.shape

(1431442, 4)

In [10]:
#Comparing the data types
activityDF.dtypes

xAccel      int64
yAccel      int64
zAccel      int64
activity    int64
dtype: object

In [11]:
activityDF['activity'].value_counts()

1    469437
7    436951
4    268320
3    150927
5     37338
2     35703
6     29320
0      3446
Name: activity, dtype: int64

In [12]:
activityDF = activityDF.drop(activityDF[activityDF.activity == 0].index)

In [13]:
activityDF['activity'].value_counts()

1    469437
7    436951
4    268320
3    150927
5     37338
2     35703
6     29320
Name: activity, dtype: int64

In [14]:
activityDF.shape

(1427996, 4)

In [15]:
activityDF.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1427996 entries, 0 to 1431440
Data columns (total 4 columns):
 #   Column    Non-Null Count    Dtype
---  ------    --------------    -----
 0   xAccel    1427996 non-null  int64
 1   yAccel    1427996 non-null  int64
 2   zAccel    1427996 non-null  int64
 3   activity  1427996 non-null  int64
dtypes: int64(4)
memory usage: 54.5 MB


In [16]:
pd.options.display.float_format = '{:,.10f}'.format
activityDF.describe()

xAccel               yAccel               zAccel  \
count 1,427,996.0000000000 1,427,996.0000000000 1,427,996.0000000000   
mean      1,959.8665878616     2,379.6311999473     1,989.5479637198   
std         108.4654587558       101.5129892019        85.7307301386   
min         282.0000000000       146.0000000000         1.0000000000   
25%       1,885.0000000000     2,337.0000000000     1,952.0000000000   
50%       1,951.0000000000     2,363.0000000000     2,001.0000000000   
75%       2,063.0000000000     2,395.0000000000     2,041.0000000000   
max       3,828.0000000000     3,997.0000000000     4,095.0000000000   

                  activity  
count 1,427,996.0000000000  
mean          3.8432677683  
std           2.4498899962  
min           1.0000000000  
25%           1.0000000000  
50%           4.0000000000  
75%           7.0000000000  
max           7.0000000000

In [17]:
activityDF.notnull().sum()

xAccel      1427996
yAccel      1427996
zAccel      1427996
activity    1427996
dtype: int64

In [18]:
#Shuffling the dataframe

activityDF = activityDF.sample(frac=1).reset_index(drop=True)

In [61]:
#MinMax Scaler for features

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
activityDF[['xAccel', 'yAccel', 'zAccel']] = scaler.fit_transform(activityDF[['xAccel', 'yAccel', 'zAccel']])

In [19]:
#Dividing the features and the class variable in to 2 dataframes

X = activityDF[['xAccel', 'yAccel', 'zAccel']]
Y = activityDF[['activity']]

In [20]:
#Importing train, test split from the Sklearn in order to split the data in to training data and testing data

from sklearn.model_selection import train_test_split
trainX, testX, trainY, testY = train_test_split(np.array(X), np.array(Y), test_size=0.2)
print(trainX.shape)
print(testX.shape)
print(trainY.shape)
print(testY.shape)

(1142396, 3)
(285600, 3)
(1142396, 1)
(285600, 1)


In [40]:
from sklearn.neighbors import KNeighborsClassifier

Kclf = KNeighborsClassifier(n_neighbors=35, weights='uniform', leaf_size=40)
fit = Kclf.fit(trainX, trainY)
y_pre = fit.predict(testX)
y_pre

/home/harindu/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  after removing the cwd from sys.path.


array([4, 4, 7, ..., 4, 7, 7])

In [41]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(testY, y_pre)
print(cm)

[[85696   310   764  2919    45    13  4161]
 [ 2658  1319   361  1668    20    16  1139]
 [ 1712   137 13386  6790   395   227  7248]
 [ 4201   207  2209 41186   146    90  5633]
 [  750    15  1156  3397   733    33  1407]
 [  326    12   855  1580   176   863  2140]
 [ 4006   129  3354  5886   126   473 73527]]


In [42]:
from sklearn.metrics import classification_report
print(classification_report(testY,y_pre))


              precision    recall  f1-score   support

           1       0.86      0.91      0.89     93908
           2       0.62      0.18      0.28      7181
           3       0.61      0.45      0.52     29895
           4       0.65      0.77      0.70     53672
           5       0.45      0.10      0.16      7491
           6       0.50      0.14      0.23      5952
           7       0.77      0.84      0.80     87501

    accuracy                           0.76    285600
   macro avg       0.64      0.48      0.51    285600
weighted avg       0.74      0.76      0.74    285600



In [43]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(testY, y_pre)
print("Accuracy: " + str(accuracy*100) + "%")

Accuracy: 75.87885154061624%
